################ Navigation English #################

# main menu
[[main]]
name = "Home"
URL = "/"
weight = 1

[[main]]
name = "About"
URL = "about/"
weight = 2
hasChildren = true

[[main]]
name = "FAQ"
URL = "faq/"
weight = 3

[[main]]
name = "Blog"
URL = "blog/"
weight = 4


[[main]]
name = "Contact"
URL = "contact/"
weight = 5


[[main]]
parent = "About"
name = "Privacy Policy"
URL = "legal/privacy-policy/"
weight = 1

[[main]]
parent = "About"
name = "Terms & Conditions"
URL = "legal/terms-conditions/"
weight = 2

[[main]]
parent = "About"
name = "Imprint"
URL = "legal/imprint/"
weight = 3


# footer menu
[[footer]]
name = "About"
URL = "about/"

[[footer]]
name = "Contact"
URL = "contact/"

[[footer]]
name = "Privacy"
URL = "legal/privacy-policy/"

[[footer]]
name = "Blog"
URL = "blog/"

[[footer]]
name = "FAQ"
URL = "faq/"